# 重新寫入 secrets.toml，因為執行環境已重設
secrets_content = """
[firebase]
type = "service_account"
project_id = "bank-cloud"
private_key_id = "8a1efea42fc1e8fb34e4211f5e582dbcff39556a"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiE/ibsJhExrfv
EX7g+KCAFNMSJxXsKE5wx8JcNJzEGQ7GO6gN3vR6EQEk+eNn4qls4CLaFH+dUQe6
Qo5U0ZdN3Vuayegx1vC6W4yxhEgLAd4zK6bMCYHyktZAm+DPvFkjKlGJNo8lHibx
oI9KpPdD0DpXIuzEJA2aZvakiD/z/T48bghrKkLcWc6WcsqiBrgkSsVwt1TirwOP
tzqzVcRBzGRrhBZAsXi2CNok0Zuq3bM/65x6s8oE61VVfnXuF3XVp4HXHGvznJRE
s1HH/9DhjIw5RlNCoAjWMgQXynd6D6a+T6yZxsobeBi19aar1yD6ryTedfo0G+zc
nOz/4b7fAgMBAAECggEAGmkPser7p6VhU9hcKPOf+mRU+phvjD0LKc8wlCQnRsBg
ixvYfXN5uf8AWpKfpDjSloEKx3zfSKFrasYCpGlHcvLhmkj8CExii14fVc6Hi3JL
+gxLEI9yDeGF08myv0G38rDS0ChEThjqNqW3rm2licwqCDM9ipPnZY678mvt+Ty7
GKPVlbWeIHa4taXQKbjAfNePyJnCwdu1fEJWRQ7rfA5J7dpCp+4InCJchmgvpVdh
EHBNObUBCZRTR6MsOM3bKGKN0kzayhYhmPO4Xe4Nz/pqTg7QMu1FhPQVcqEYkwOw
F1Zt1rQSKlIVrvEDJJ55cIUkUtp6DSzJh+5//GqqQQKBgQDfKBjYiDZZ0lgcbV9P
HtNphzhflQLITx0O94v7ELB2jPGMkFTS5dG5yIvHtjKyX5Dhiyt+8lu0pPpddsom
eit5El+k8se7t9XypwZloMEdA1MFFf8AdlV8t7tX1rkRp+jTEkz3emT32C1IR2cz
M3ntX7qTjrNJBbrhAi1uVqznwQKBgQC57ptMq/flxuahqbV1CxI8n9frXan2AIX1
DwKLKEfS9XoAQ/QLVw3Oj7QB/zbYD8oJ55HzFAC+dWhMvk2umAicWJSm5ATaEN47
MqxZ+yJwG1DPT1QBo6zt6TcqaMKpP0shOG32KsyE+uMYe5iyb+5evCFpK7Qciira
VYO5nCFOnwKBgCYpDi6hBGJRxP1/eofmJpLqK6q0qZglZzuy+z4AuZxcN8YovEig
Qj/52mVZc8vq6bSX/uUjfqkieSnYcXMo+xwmFzL2zU79fdmT1FU2qy9R7TV2cHfc
xHuiU6gOsPEi/H5zp7O+O1vinMO6ahxoVhZQg3BOO7xl/XIS1EAFFGZBAoGAI+FW
2NHq0c2zXgko+kA7sbVK7qGxlcZ+E09lN0N7sMssUvbKFpIjGPSEUUpV5BYP8B9e
++ClUBvKF901knbGWp2Bej9QbGCK8jOSLP8YozeyPX9af8J9MaAqxCVZQ13yeqOw
HKwfsZ3Uyzm2uuB8yI1XiTsk08kaAe40sFHf35MCgYEAxctb3XHKFnE5urxgLx6S
1D59+ESfGuE93NB7fQOpIXi0rd+g4rPwuUCqmsFpZ2QNSO8wBHdIA//M6NGhZhHJ
36et/vl8JM0YCPWM7fK2Gp9ODOKRYTvluuV+8D9BZUygEn28pKPFLdaJRUH/LC+B
EZUjxdRq68OpcC647yskp9g=
-----END PRIVATE KEY-----'''
client_email = "firebase-adminsdk-fbsvc@bank-cloud.iam.gserviceaccount.com"
client_id = "100768766069571124471"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40bank-cloud.iam.gserviceaccount.com"
"""

with open("/mnt/data/secrets.toml", "w") as f:
    f.write(secrets_content)

"/mnt/data/secrets.toml"
